using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
    // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
    //       Changes made to the 'designer' file will be overwritten by the wizard.  	
    public partial class Appointment
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Appointment()
        {
        }

        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }

        [Telerik.OpenAccess.FieldAlias("annotations")]
        public string Annotations
        {
            get { return annotations; }
            set { this.annotations = value; }
        }

        [Telerik.OpenAccess.FieldAlias("description")]
        public string Description
        {
            get { return description; }
            set { this.description = value; }
        }

        [Telerik.OpenAccess.FieldAlias("end1")]
        public DateTime End1
        {
            get { return end1; }
            set { this.end1 = value; }
        }

        [Telerik.OpenAccess.FieldAlias("recurrenceParentID")]
        public int? RecurrenceParentID
        {
            get { return recurrenceParentID; }
            set { this.recurrenceParentID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("recurrenceRule")]
        public string RecurrenceRule
        {
            get { return recurrenceRule; }
            set { this.recurrenceRule = value; }
        }

        [Telerik.OpenAccess.FieldAlias("roomID")]
        public int? RoomID
        {
            get { return roomID; }
            set { this.roomID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("start")]
        public DateTime Start
        {
            get { return start; }
            set { this.start = value; }
        }

        [Telerik.OpenAccess.FieldAlias("subject")]
        public string Subject
        {
            get { return subject; }
            set { this.subject = value; }
        }

        [Telerik.OpenAccess.FieldAlias("userID")]
        public int? UserID
        {
            get { return userID; }
            set { this.userID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("appointment1")]
        public Appointment Appointment1
        {
            get { return appointment1; }
            set { this.appointment1 = value; }
        }

        [Telerik.OpenAccess.FieldAlias("room")]
        public Room Room
        {
            get { return room; }
            set { this.room = value; }
        }

        [Telerik.OpenAccess.FieldAlias("user")]
        public User User
        {
            get { return user; }
            set { this.user = value; }
        }


    }
}
