using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
    // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
    //       Changes made to the 'designer' file will be overwritten by the wizard.  	
    public partial class CustomerDemographic
    {
        //The 'no-args' constructor required by OpenAccess. 
        public CustomerDemographic()
        {
        }

        [Telerik.OpenAccess.FieldAlias("customerTypeID")]
        public string CustomerTypeID
        {
            get { return customerTypeID; }
            set { this.customerTypeID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("customerDesc")]
        public string CustomerDesc
        {
            get { return customerDesc; }
            set { this.customerDesc = value; }
        }

        [Telerik.OpenAccess.FieldAlias("customerCustomerDemo")]
        public IList<Customer> CustomerCustomerDemos
        {
            get { return customerCustomerDemo; }
        }


    }
}
