

using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField = "customerTypeID")]
    public partial class CustomerDemographic
    {
        private string customerTypeID; // pk 

        private string customerDesc;

        private IList<Customer> customerCustomerDemo = new List<Customer>();





    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace TRData 
{
    //Generated by Telerik OpenAccess
    public partial class CustomerDemographic 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public CustomerDemographic() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("customerTypeID")]
        public string CustomerTypeID
        {
            get { return customerTypeID; }
            set { this.customerTypeID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("customerDesc")]
        public string CustomerDesc
        {
            get { return customerDesc; }
            set { this.customerDesc = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("customerCustomerDemo")]
        public IList<Customer> CustomerCustomerDemos
        {
            get { return customerCustomerDemo; }
        }
 

    }
}
*/
#endregion //main class file contents
