using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
    // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
    //       Changes made to the 'designer' file will be overwritten by the wizard.  	
    public partial class Product
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Product()
        {
        }

        [Telerik.OpenAccess.FieldAlias("productID")]
        public int ProductID
        {
            get { return productID; }
            set { this.productID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("categoryID")]
        public int? CategoryID
        {
            get { return categoryID; }
            set { this.categoryID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("discontinued")]
        public bool Discontinued
        {
            get { return discontinued; }
            set { this.discontinued = value; }
        }

        [Telerik.OpenAccess.FieldAlias("productName")]
        public string ProductName
        {
            get { return productName; }
            set { this.productName = value; }
        }

        [Telerik.OpenAccess.FieldAlias("quantityPerUnit")]
        public string QuantityPerUnit
        {
            get { return quantityPerUnit; }
            set { this.quantityPerUnit = value; }
        }

        [Telerik.OpenAccess.FieldAlias("reorderLevel")]
        public short? ReorderLevel
        {
            get { return reorderLevel; }
            set { this.reorderLevel = value; }
        }

        [Telerik.OpenAccess.FieldAlias("supplierID")]
        public int? SupplierID
        {
            get { return supplierID; }
            set { this.supplierID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("unitPrice")]
        public Decimal? UnitPrice
        {
            get { return unitPrice; }
            set { this.unitPrice = value; }
        }

        [Telerik.OpenAccess.FieldAlias("unitsInStock")]
        public short? UnitsInStock
        {
            get { return unitsInStock; }
            set { this.unitsInStock = value; }
        }

        [Telerik.OpenAccess.FieldAlias("unitsOnOrder")]
        public short? UnitsOnOrder
        {
            get { return unitsOnOrder; }
            set { this.unitsOnOrder = value; }
        }

        [Telerik.OpenAccess.FieldAlias("category")]
        public Category Category
        {
            get { return category; }
            set { this.category = value; }
        }

        [Telerik.OpenAccess.FieldAlias("supplier")]
        public Supplier Supplier
        {
            get { return supplier; }
            set { this.supplier = value; }
        }


    }
}
