

using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField = "regionID")]
    public partial class Region
    {
        private int regionID; // pk 

        private string regionDescription;





    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace TRData 
{
    //Generated by Telerik OpenAccess
    public partial class Region 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Region() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("regionID")]
        public int RegionID
        {
            get { return regionID; }
            set { this.regionID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("regionDescription")]
        public string RegionDescription
        {
            get { return regionDescription; }
            set { this.regionDescription = value; }
        }
 

    }
}
*/
#endregion //main class file contents
