

using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField = "shipperID")]
    public partial class Shipper
    {
        private int shipperID; // pk 

        private string companyName;

        private string phone;





    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace TRData 
{
    //Generated by Telerik OpenAccess
    public partial class Shipper 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Shipper() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("shipperID")]
        public int ShipperID
        {
            get { return shipperID; }
            set { this.shipperID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("companyName")]
        public string CompanyName
        {
            get { return companyName; }
            set { this.companyName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("phone")]
        public string Phone
        {
            get { return phone; }
            set { this.phone = value; }
        }
 

    }
}
*/
#endregion //main class file contents
