//Copyright (c) Telerik.  All rights reserved.

using System;
using System.Collections.Generic;
using Telerik.OpenAccess;

namespace TRData
{
    /// <summary>
    /// This class holds static methods defined to invoke user defined stored procedures
    /// </summary>
    /// <remarks>
    /// <para>
    /// It is generated by the Reverse Engineering wizard. 
    /// </para>
    /// </remarks>
   
   public static class StoredProcedure
   {
        public static IQueryResult TenMostExpensiveProducts(IObjectScope scope)
        {
            IQuery query = scope.GetSqlQuery("[Ten Most Expensive Products]",null,"");
            
            IQueryResult res = query.Execute(new object[] {});
            int a = res.Count;//Actually executes the query
            
            
            
            return res;
        }

   }
 }




