

using System;
using System.Collections.Generic;

namespace TRData
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField = "id")]
    public partial class User
    {
        private int id; // pk 

        private string userName;





    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace TRData 
{
    //Generated by Telerik OpenAccess
    public partial class User 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public User() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userName")]
        public string UserName
        {
            get { return userName; }
            set { this.userName = value; }
        }
 

    }
}
*/
#endregion //main class file contents
